// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int64     `json:"id"`
	SessionID string    `json:"session_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Email            string         `json:"email"`
	PasswordHash     string         `json:"password_hash"`
	Verified         bool           `json:"verified"`
	VerificationCode sql.NullString `json:"verification_code"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}
