Table users {
  id bigserial [primary key]
  email varchar [not null, unique]
  password_hash varchar [not null]
  verified boolean [not null]
  verification_code varchar
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  Indexes {
    email
  }
}

Table sessions {
  id bigserial [primary key]
  session_id varchar [unique, not null]
  user_id bigint [not null, ref: - users.id]
  created_at timestamp [not null, default: `now()`]
  expires_at timestamp [not null]

  Indexes {
    session_id
  }
}